num = int(input('Digite o numero para a sua tabuáda: '))
one = num * 1
two = num * 2
three = num * 3
four = num * 4
five = num * 5
six = num * 6
seven = num * 7
eight = num * 8
nine = num * 9
teen = num * 10
print('\n{} x 1 = {}\n'.format(num, one))
print('{} x 2 = {}\n'.format(num, two))
print('{} x 3 = {}\n'.format(num, three))
print('{} x 4 = {}\n'.format(num, four))
print('{} x 5 = {}\n'.format(num, five))
print('{} x 6 = {}\n'.format(num, six))
print('{} x 7 = {}\n'.format(num, seven))
print('{} x 8 = {} \n'.format(num, eight))
print('{} x 9 = {}\n'.format(num, nine))
print('{} x 10 ={}\n'.format(num, teen))
