info = input('Digite Algo: ')
print('O tipo primitivo do valor {}, é: '.format(info), type(info))
print('{} só tem espaços?'.format(info), info.isspace())
print('{} É um Numero? '.format(info), info.isnumeric())
print('{} É um Numero Decimal? '.format(info), info.isdecimal())
print('{} É Alfabético? '.format(info), info.isalpha())
print('{} É Alfanumerico? '.format(info), info.isalnum())
print('{} Está em Maiuscula? '.format(info), info.isupper())
print('{} Está em minusculas? '.format(info), info.islower())
print('{} Está Capitalizada?'.format(info), info.istitle())
